version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-python-crud-sample"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wtzge5we4xwv"
s3_prefix = "sam-python-crud-sample"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Table=\"Bikes\" Region=\"eu-west-1\" AWSEnv=\"AWS\""
image_repositories = []
